# https://salsa.debian.org/rust-team/debcargo/blob/master/debcargo.toml.example
overlay = "./debian"
summary = "Use Universal Plug and Play (UPnP) to expose your Peach device to the internet via your router"
description = """
A simple wrapper around miniupnpc
"""

[source]
section = "rust"
vcs_git = "git://github.com/peachcloud/peach-upnp.git"
vcs_browser = "https://github.com/peachcloud/peach-upnp"

[packages.bin]
section = "net"
depends = ["miniupnpc"]
